### ISSUE TITLE
bzImage?

### ISSUE THREAD

**Issue by kbumsik** [MichielDerhaeg/build-linux#10]
Hello, I am very new to building Linux. Firstly thank you for this nice article.
So I tried to follow your explanation but I was suck here:

> We'll copy our binaries over.
> 
>> $ cp /path/to/busybox usr/bin/busybox
>> $ cp /path/to/bzImage boot/bzImage

`bzImage` appeared all of the sudden, without being mentioned until now. Newcomers to Linux like me may have no idea what does `bzImage` means and where to find the `bzImage` (although when I figured it out by looking through your Makefile).

**Comment by MichielDerhaeg** [comment]
Good point. I should mention that it's the kernel you built and that the linux makefile tells you where you can find it when it's done.

**Comment by MichielDerhaeg** [comment]
631e5bf5a9a97b1b49bcc43e835602b0f148c3e4
This should make it clear I think.
