### ISSUE TITLE
Rethinking boot process and initramfs

### ISSUE THREAD

**Issue by imrn** [MichielDerhaeg/build-linux#11]
Here are my thoughts and experiments about the subject:

Initramfs hides a lot and brings unnecesary complexity eventhough
it is unneeded in 99% of the cases. So starting with an extracted
initramfs I've ended up with the attached init on /boot.

Machine boots from /boot straight and pivots to /.  No initramfs
employed. Contents of /boot is always accessible and editable.
I can provide more details if there is further interest.

/boot only has the following (About 6MB in total):
- syslinux
- Linux kernel: Minimal one with necessary modules built-in.
(Just enough to mount and pivot to /. devtmpfs included and auto mounted)
- Busbox
- Fonts and keymaps
(Needed for proper luks password entry on non-US setups)
- init script. See below.

Suggested common disk layout:
/dev/sda1 -> /boot  - 128M btrfs created  with -M mixed mode
/dev/sda2 -> /  compressed btrfs on luks. (or f2fs for flash/SSD) 

```shell
#!/bin/ash
setfont  /boot/lat5-16.psfu.gz  -C /dev/console &
loadkmap < /boot/trq.bmap &

# backgrounding with '&' is for utilizing parallel execution and
# cutting some boot seconds. You can also use it elsewhere.
# But NOT below! These lines should execute sequentially.
# Use '&' wisely.

mount  -t proc  proc  /proc  -o nosuid,noatime,nodev,noexec
# add crypt_setup lines here.
mount  /dev/sda2  /mnt
cd  /mnt
mount  --move  /dev  ./dev
mount  --move  /proc  ./proc
pivot_root   .  boot
exec chroot  .  /bin/init
```

**Comment by MichielDerhaeg** [comment]
So the advantages of this is that the initfs is editable. Only seems useful though when you're doing stuff like LUKS, like you are. What do you want to do with this?

**Comment by imrn** [comment]
I don't have any specific request for that. I'm already using it.
It's just a note for a light weight distro which might need some
minimal boot before real root booting. Yes; LUKS is one case for it.

**Comment by MichielDerhaeg** [comment]
You make a good point, I might do something similar when I switch over to LUKS or something like that.

**Comment by imrn** [comment]
Even before that you may also consider providing syslinux
as a bootloader option. It is lightweight and rock solid.
You can just edit the lean syslinux.cfg and continue.
No config generation or any other thing. With that spirit
it is more appropriate for "Accessible /boot" suggestion.

**Comment by MichielDerhaeg** [comment]
Syslinux probably was a better option for the tutorial. I just used GRUB
because that's what I'm familiar with.
