### ISSUE TITLE
Busybox issue

### ISSUE THREAD

**Issue by visar** [MichielDerhaeg/build-linux#13]
While running `make all` (specifically, `make busybox`) I ran into this issue:

```
console-tools/kbd_mode.c:33:22: fatal error: linux/kd.h: No such file or directory
 #include <linux/kd.h>
                      ^
compilation terminated.
scripts/Makefile.build:197: recipe for target 'console-tools/kbd_mode.o' failed
make[2]: *** [console-tools/kbd_mode.o] Error 1
Makefile:742: recipe for target 'console-tools' failed
make[1]: *** [console-tools] Error 2
make[1]: Leaving directory '/home/vnz/work/build-linux/busybox-1.26.2'
Makefile:26: recipe for target 'busybox' failed
make: *** [busybox] Error 2
[1]    27046 exit 2     make busybox
```

Any idea on how should this be resolved?

**Comment by MichielDerhaeg** [comment]
This happens because it's not using the sanitized kernel headers to
build busybox. That might be because those headers are in a git
submodule and you haven't cloned them too. Try to do ``git submodule
update --init`` and see if that fixes it.

**Comment by visar** [comment]
Yes, that fixes it. This happens only on Ubuntu and Debian, on Arch systems one does not need to download the gitmodules. Thanks.

PS maybe you should put that on the README.

**Comment by MichielDerhaeg** [comment]
Yeah, Arch supplies those kernel headers via a package. The README
mentions where you can get those headers. I should find a place to
mention that about the submodule somewhere.
