### ISSUE TITLE
Remounting /dev without initramfs *can* hurt

### ISSUE THREAD

**Issue by ghost** [MichielDerhaeg/build-linux#18]
Mounting `/dev` when Linux has already mounted it causes `mount` to fail (at least in my case) with `resource busy`.

**Comment by MichielDerhaeg** [comment]
It fails because it's already mounted, so why does it matter that ``mount`` fails if the right filesystem is already mounted?

**Comment by MichielDerhaeg** [comment]
Also, it's a normal mount, not a remount.

**Comment by ghost** [comment]
Yes, sorry about the phrasing. The reason it matters is that it causes an
error message and breaks my boot script. It can be easily fixed by just
removing the mount. If it's unnecessary, it probably shouldn't be done. :)

**Comment by MichielDerhaeg** [comment]
The cleanest way would be checking if it's a mount point first, like so
```bash
mountpoint -q /dev || mount -t devtmpfs dev /dev
```
But mount failing shouldn't break your script, just print an error. So for the sake of keeping it simple, the ``mountpoint -q`` part was omitted.

**Comment by ghost** [comment]
Maybe note that an error might happen, but that it's not a problem?

**Comment by MichielDerhaeg** [comment]
Good point, I'll put that in somewhere.
