### ISSUE TITLE
Kernel Panic on real hardware. (not a dupe)

### ISSUE THREAD

**Issue by SamHep0803** [MichielDerhaeg/build-linux#21]
I keep getting the same error as with the other issue, but the only difference is that I'm trying it on real hardware.

To be specific a PC with windows installed on it. However, I'm having trouble getting it to even boot as I'm getting a kernel panic. Also, I'm using the Makefile provided.

To be honest, I have no clue what to do.

Thanks, Sam.

**Comment by MichielDerhaeg** [comment]
My guess would be that the kernel doesn't have the required components
built in to support your system. But I can only speculate without more
information. What are you using to boot? What does the kernel panic say
exactly?

**Comment by SamHep0803** [comment]
As I said, it's the same error as the last kernel panic issue. However, It works in qemu, just not my test system.

`kernel panic - not syncing vfs unable to mount root fs on unknown-block (0 0)`

There.

**Comment by SamHep0803** [comment]
I'm using a custom build system

**Comment by SamHep0803** [comment]
Would be grateful for a reply?

**Comment by MichielDerhaeg** [comment]
Sorry, I have very little time these days. I may be overlooking
something, but which previous kernel panic issue are you referring to?

**Comment by SamHep0803** [comment]
As issued in #8 .

**Comment by MichielDerhaeg** [comment]
Ah, i see, could you tell me what kind of system you're currently using
to build and could you give me the output of 'fdisk -l image'?

**Comment by SamHep0803** [comment]
I'm currently using Ubuntu 18.04 LTS and fdisk shows:

```
Disk build-linux/image: 100 MiB, 104857600 bytes, 204800 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xb8e75e52

Device             Boot Start    End Sectors Size Id Type
build-linux/image1       2048 204799  202752  99M 83 Linux
```

**Comment by MichielDerhaeg** [comment]
It might not be able to interpret PARTUUIDs, i suggest editting gen_image.sh to set `root=PARTUUID=..`
to `root=/dev/sda1` or `root=/dev/sdb1`, whatever works, and trying again.

**Comment by SamHep0803** [comment]
ok

**Comment by MichielDerhaeg** [comment]
Or just by mounting, and manually editting /boot/grub/grub.cfg, whatever floats your boat.

**Comment by SamHep0803** [comment]
So should I set it to what my USB drive is mounted at now?

**Comment by MichielDerhaeg** [comment]
If you're using the same system to boot it, yes. It might be slightly non-deterministic but it's probably right.

**Comment by SamHep0803** [comment]
No, I'm not using the same system. It's a different system with a windows SSD in it.

**Comment by MichielDerhaeg** [comment]
In that case you'll have to do some trial and error.

**Comment by SamHep0803** [comment]
i seem to be getting the same error o
in vbox now.

**Comment by MichielDerhaeg** [comment]
It's hardware specific, so trying it first in vbox has no use.

**Comment by SamHep0803** [comment]
the only reason im trying it in vbox is bc it was working before

**Comment by SamHep0803** [comment]
So, I booted it up on my machine again only to find out I have *another* kernel panic. Buuut it's a different error. I can't see the whole error but the last line reads.

`[    0.989140] ---[end trace efb985e050e98130 ]---`

**Comment by MichielDerhaeg** [comment]
Have you tried other options? You might have selected the Windows disk. Also, it just occurred to me that the kernel configuration you used might not have the required components enabled to boot from your particular system and USB drive. Configuring that correctly might be difficult for someone who hasn't done that before.

**Comment by MichielDerhaeg** [comment]
Usually kernels are built to support all sorts of hardware, but in this case it's mainly to support VM's.

**Comment by SamHep0803** [comment]
Hmm I’m sure I didn’t select my windows drive and even after changing the gen-image.sh file my vm still didn’t work. I’m stumped at this point.

**Comment by MichielDerhaeg** [comment]
Well, so am I, I'm guessing it's a kernel configuration issue. And those sorts of things are way to hard to diagnose like this :S

**Comment by SamHep0803** [comment]
Ugh... Well I’ll have to call it a day till I get back to my PC, do you have discord?

**Comment by MichielDerhaeg** [comment]
Yep, send me a mail about it when you want to get in touch.
I'm going to close this issue for now.
