### ISSUE TITLE
What do i need for this?

### ISSUE THREAD

**Issue by StarTrekRules** [MichielDerhaeg/build-linux#23]
What do i need?
I read the readme and it has stuff like bin/sh and sbin/init, i could not find anything on sbin/init so i just made my own and that didn't work, messing with the grub.cfg init parameter didn't help either 
`Requested init /sbin/init failed (error -13)`

**Comment by nicolasdanelon** [comment]
have you ever try googling the quoted text?

**Comment by nicolasdanelon** [comment]
https://www.google.com/search?q=Requested+init+%2Fsbin%2Finit+failed+(error+-13)
