### ISSUE TITLE
grub-install: Error cannot find EFI directory 

### ISSUE THREAD

**Issue by Lw-Cui** [MichielDerhaeg/build-linux#5]
Hi Michiel,
I use Ubuntu 16.04 and when doing `grub-install --boot-directory="$PWD/boot" /dev/loop0` I got error `grub-install: cannot find EFI directory`.
How should I fix it? 
Thanks.

**Comment by Shuliyey** [comment]
@Lw-Cui 

By default grub-install uses `x86_64-efi`, you might need the `--target=i386-pc` flag, alternatively you can specify the `--efi-directory` flag

https://bbs.archlinux.org/viewtopic.php?id=178423

**Comment by MichielDerhaeg** [comment]
Yeah, I kindof mentioned this in the docs. GRUB defaults to EFI on your system, so you have to specify that you want to use the old MBR BIOS bootloader with the ``--target=i386-pc``. If you followed the docs, this is required. An EFI installation would require a GPT partition table and an EFI partition.

**Comment by Lw-Cui** [comment]
Thanks.
But when using `--target=i386-pc` it said `grub-install：Error /usr/lib/grub/i386-pc/modinfo.sh doesn't exist. Please specify --target or --directory.`
Does that mean I need install 32bit version?

**Comment by MichielDerhaeg** [comment]
@ric96 mentioned that you might need to install ``grub-pc-bin`` first on Ubuntu if your system uses EFI, could you try that?

**Comment by Lw-Cui** [comment]
Yes this issue has been moved forward:)
But now qemu show `error: no such device: 1da96cd4-faaf-4a02-ac75-ec0bc60e4b65.`
Maybe it's wrong `PARTUUID` number?
Thanks for your patience!

**Comment by MichielDerhaeg** [comment]
Did you add the ``--modules=part_msdos`` option to ``grub-install``?

**Comment by Lw-Cui** [comment]
Yes. I tried `grub-install` again to make sure it has this option.

**Comment by MichielDerhaeg** [comment]
And the issue persists?

**Comment by Lw-Cui** [comment]
Yes. 
By the way I replaced it using `root=/dev/sda1` and this error still occurred, while qemu with `root=/dev/sda1` works fine all the time.

**Comment by MichielDerhaeg** [comment]
The ``root`` option in grub.cfg isn't used by GRUB to determine the root device, it's for the kernel. The root devices is determined by GRUB when you do ``grub-install``. Do you have the same issue when using the makefile to build the image?

**Comment by Shuliyey** [comment]
what's the output of

```
fdisk -l image
```

and this line in `boot/grub/grub.cfg`

```
linux /boot/bzImage quiet init=/bin/sh root=PARTUUID=........
boot
```

**Comment by Lw-Cui** [comment]
@Shuliyey 
`fdisk -l image` is
```
Disk image: 100 MiB, 104857600 bytes, 204800 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x02170d17

设备       启动 Start 末尾 扇区 Size Id 类型
image1           2048 204799 202752  99M 83 Linux
```
and `boot/grub/grub.cfg` is
```

linux /boot/bzImage quiet init=/bin/sh root=PARTUUID=02170d17-01
boot
```

**Comment by Lw-Cui** [comment]
@MichielDerhaeg 
OK I will try Makefile tomorrow, currently I build them by hand.
You write awesome instruction:)

**Comment by Shuliyey** [comment]
can you try upload your `grub.cfg` and `/etc/fstab`, i got a feeling it's something to do one of these two @Lw-Cui

**Comment by MichielDerhaeg** [comment]
@Lw-Cui 
Thanks!
@Shuliyey 
I disagree, I believe this is an error caused ``grub-install`` not installing the right modules so it can find the right filesystem. I think this error occurs before any file can even be read.

**Comment by MichielDerhaeg** [comment]
I could confirm my suspicion if you would do ``grub-install`` with the ``--verbose`` option and pass me the output somehow.

**Comment by Shuliyey** [comment]
i see, that make sense cheers @MichielDerhaeg

**Comment by Lw-Cui** [comment]
@MichielDerhaeg Yes Makefile works well! Thanks a lot:)
Then I could re-execute those commands by hand and find what's going wrong.
