### ISSUE TITLE
How to add more software to my system? How to boot on hardware?

### ISSUE THREAD

**Issue by minecrawler** [MichielDerhaeg/build-linux#6]
The tutorial is really nice and kept quite simple (I don't know if it is too simple for beginners starting from Ubuntu). It definitely is a good guide for people who already know a thing or two about Linux (I might be able to use it, however I run Gentoo on my Desktop ;P), so thank you a lot for putting your time into writing it.

There is, however, one thing which I am missing: How do I boot my system and then install new software? You are missing that part completely. You should add a little guide detailing how to add gcc or Clang and git to the system, so that source code can be fetched and compiled.

Also a little guide on how to prepare that system for installation on hardware would be nice ;)

**Comment by MichielDerhaeg** [comment]
I thought about adding a part about installing new software. But I'm not sure if I should explain how to build a toolchain for the system, which is a rather long and tedious process. Or how to use the toolchain available on your current system to build the software, a bit similar in the way cross-compilation is done, which is simpler.

Installation on hardware should be trivial I think, you could substitute the disk image for an actual disk. Or when you're done just ``dd if=image of=/dev/actualdisk bs=1M``. But you're right I didn't really mention anything about that. Maybe I should add that somewhere too.

**Comment by nicolasdanelon** [comment]
_But you're right I didn't really mention anything about that. Maybe I should add that somewhere too._
Yes please :)
hahaha I was going to create this issue too :P ahaha 
good job @MichielDerhaeg !! thanks 4 this tuto!

**Comment by leahcornelius** [comment]
Any news on this? I would be interested on how one might compile a toolchain for it as i am hoping toget x start to work with ti to add a gui.
