### ISSUE TITLE
fs.tar missing?

### ISSUE THREAD

**Issue by ghost** [MichielDerhaeg/build-linux#7]
gen-image.sh refers to fs.tar, am assuming its the filesystem folder?

**Comment by MichielDerhaeg** [comment]
Take a look at the makefile, it runs the makefile in filesystem/ which produces the fs.tar before running gen_image.sh

**Comment by ghost** [comment]
Ah ha, I see... Plan on using stock Arch kernel and busybox static (as its pre-built). Have done something similar with minimal linux. Only I never managed to a working console.
