### ISSUE TITLE
Kernel Panic

### ISSUE THREAD

**Issue by Srl3nny** [MichielDerhaeg/build-linux#8]
Hi
Congratulations for the tuto.
I get the message druring the boot.
 **kernel panic - not syncing vfs unable to mount root fs on unknown-block (0 0)**

I tried change grub.cfg to root=/dev/sda{1,2,3,4} and did not work.

My disk identifier is  0x1593f630

> $ cat image-root/boot/grub/grub.cfg 
> linux /boot/bzImage quiet init=/bin/sh root=PARTUUID=1593f630-01
> boot

I use Debian 8.

tks

**Comment by MichielDerhaeg** [comment]
Could you do ``fdisk -l image`` and give me the output?

**Comment by Srl3nny** [comment]
The fdisk -l is 

> sudo fdisk -l image
> 
> Disco image: 400 MiB, 419430400 bytes, 819200 setores
> Unidades: setor de 1 * 512 = 512 bytes
> Tamanho de setor (lógico/físico): 512 bytes / 512 bytes
> Tamanho E/S (mínimo/ótimo): 512 bytes / 512 bytes
> Tipo de rótulo do disco: dos
> Identificador do disco: 0x1593f630
> 
> Device     Boot Start    End Sectors  Size Id Type
> image1           2048 819199  817152  399M 83 Linux

**Comment by MichielDerhaeg** [comment]
Weird, looks like the kernel doesn't know what to do with the filesystem or the disk interface. Did you configure your kernel differently? Launched qemu with different options?

**Comment by Srl3nny** [comment]
Hi Michiel

I configure the kernel and launched qemu like your tutorial, I'll try again later in my workstation that has a Ubuntu 16.04 and tell here the result.

tks

**Comment by kbumsik** [comment]
Hi Michiel,
I have exactly same problem with `PARTUUID`. But I changed it to `root=/dev/sda1` and it works.
I use Ubuntu Gnome 16.04.2 LTS on VMware Workstation though.

**Comment by guinanseyebrows** [comment]
I also experienced kernel panics during boot. I reformatted my loop device as ext3 and it worked perfectly, so maybe my .config wasn't working properly with ext4 support. odd, but i'm not too worried about that for now. i'm building this on void musl.

**Comment by Srl3nny** [comment]
I use Ubuntu 16.04 and it work. 
But i can't install the bootloader, I get the error

> grub-install: erro: /usr/lib/grub/i386-pc/modinfo.sh doesn't exist. Please specify --target or --directory.

I think that is because the grub packages in my machine:
grub-common, grub-efi-amd64, grub-efi-amd64-bin, grub-efi-amd64-signed, grub2-common

I used QEMU to load the kernel, and work, now I can continue.

**Comment by MichielDerhaeg** [comment]
That error happens because you need the `grub-pc-bin` package.

**Comment by Srl3nny** [comment]
Ok, bootloader installed.
Tks
